# Generated by Django 4.2.3 on 2023-07-09 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
    ]
