# Generated by Django 4.2.3 on 2023-07-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0002_tag_table_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="tags",
            field=models.ManyToManyField(default=None, to="screenshots.tag"),
        ),
    ]
