# Generated by Django 4.2.3 on 2023-07-09 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0003_added_tags_to_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
