# Generated by Django 4.2.3 on 2023-08-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0004_added_owner_to_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="name",
            field=models.CharField(default="default", max_length=128),
            preserve_default=False,
        ),
    ]
