# Generated by Django 4.2.3 on 2023-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0006_altered_owner_to_CASCADE_in_screenshot_and_tag_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screenshot",
            name="file_url",
        ),
        migrations.AddField(
            model_name="screenshot",
            name="description",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="screenshot",
            name="filename",
            field=models.CharField(default="filename.png", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screenshot",
            name="format",
            field=models.CharField(default=".png", max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screenshot",
            name="height",
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screenshot",
            name="image_url",
            field=models.URLField(default="https://test.fr", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screenshot",
            name="size",
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screenshot",
            name="thumbnail_url",
            field=models.URLField(default="https://test.fr", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screenshot",
            name="width",
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
