# Generated by Django 4.2.3 on 2023-08-13 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0007_added_data_fields_to_screenshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "db_table": "applications",
            },
        ),
        migrations.AddField(
            model_name="screenshot",
            name="application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="screenshots.application",
            ),
        ),
    ]
