# Generated by Django 4.2.3 on 2023-08-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0009_added_user_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
