# Generated by Django 4.2.3 on 2023-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0010_added_owner_to_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="image_hash",
            field=models.CharField(default=123, max_length=32),
            preserve_default=False,
        ),
    ]
